[package]
name = "cargo-near"
version.workspace = true
edition = "2021"

[dependencies]
cargo-near-lib = { path = "../cargo-near-lib" }
color-eyre = "0.6.3"
tracing-error = "0.2.0"
tracing = "0.1.13"

tracing-subscriber = { version = "0.3.0", features = ["env-filter"]}
